package dbService.dao;

import dbService.dao.Exceptions.ArraysLengthsMismathException;
import dbService.dao.Exceptions.UnhandledArgumentTypeException;
import dbService.dataSets.UsersDataSet;
import dbService.executor.Executor;

import java.sql.SQLException;
import java.util.ArrayList;

public class DAO {
    public DAO(Executor executor) {
        this.executor = executor;
    }

    private final Executor executor;

    public void createUsersTable() {
        executor.execUpdate("""
                create table if not exists users (
                     id bigint generated by default as identity,
                     login varchar(256),
                     password varchar(256),
                     primary key (id)
                 )""");
    }

    public UsersDataSet getUserById(long id) throws ArraysLengthsMismathException {
        return executor.execQuery("""
                        select tu.id, u.login, u.password
                        from users u where u.id = ?""",
                1,
                new Class[] { Long.class },
                new Object[] { id },
                rs -> {
                    ArrayList<UsersDataSet> resultObjList = new ArrayList<>();
                    while(!rs.isLast()) {
                        rs.next();
                        resultObjList.add(new UsersDataSet(
                                rs.getLong(1),
                                rs.getString(2),
                                rs.getString(3)));
                    }
                    return resultObjList;
                }).get(0);
    }
}
