DROP TABLE IF EXISTS parallel_tests.ranges;
CREATE TABLE IF NOT EXISTS parallel_tests.ranges (
	id			INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
	t_name		TEXT NOT NULL,
	row_from	INT4 NOT NULL,
	row_to		INT4 NOT NULL,
	call_flag	BOOLEAN DEFAULT FALSE NOT NULL
);

INSERT INTO parallel_tests.ranges (t_name, row_from, row_to) VALUES ('to_block_01',   1, 100);
INSERT INTO parallel_tests.ranges (t_name, row_from, row_to) VALUES ('to_block_01', 101, 200);
INSERT INTO parallel_tests.ranges (t_name, row_from, row_to) VALUES ('to_block_01', 201, 300);
INSERT INTO parallel_tests.ranges (t_name, row_from, row_to) VALUES ('to_block_01', 301, 400);
INSERT INTO parallel_tests.ranges (t_name, row_from, row_to) VALUES ('to_block_01', 401, 500);

INSERT INTO parallel_tests.ranges (t_name, row_from, row_to) VALUES ('to_block_02',   1, 100);
INSERT INTO parallel_tests.ranges (t_name, row_from, row_to) VALUES ('to_block_02', 101, 200);
INSERT INTO parallel_tests.ranges (t_name, row_from, row_to) VALUES ('to_block_02', 201, 300);
INSERT INTO parallel_tests.ranges (t_name, row_from, row_to) VALUES ('to_block_02', 301, 400);
INSERT INTO parallel_tests.ranges (t_name, row_from, row_to) VALUES ('to_block_02', 401, 500);

INSERT INTO parallel_tests.ranges (t_name, row_from, row_to) VALUES ('to_block_03',   1, 100);
INSERT INTO parallel_tests.ranges (t_name, row_from, row_to) VALUES ('to_block_03', 101, 200);
INSERT INTO parallel_tests.ranges (t_name, row_from, row_to) VALUES ('to_block_03', 201, 300);
INSERT INTO parallel_tests.ranges (t_name, row_from, row_to) VALUES ('to_block_03', 301, 400);
INSERT INTO parallel_tests.ranges (t_name, row_from, row_to) VALUES ('to_block_03', 401, 500);

INSERT INTO parallel_tests.ranges (t_name, row_from, row_to) VALUES ('to_block_04',   1, 100);
INSERT INTO parallel_tests.ranges (t_name, row_from, row_to) VALUES ('to_block_04', 101, 200);
INSERT INTO parallel_tests.ranges (t_name, row_from, row_to) VALUES ('to_block_04', 201, 300);
INSERT INTO parallel_tests.ranges (t_name, row_from, row_to) VALUES ('to_block_04', 301, 400);
INSERT INTO parallel_tests.ranges (t_name, row_from, row_to) VALUES ('to_block_04', 401, 500);

INSERT INTO parallel_tests.ranges (t_name, row_from, row_to) VALUES ('to_block_05',   1, 100);
INSERT INTO parallel_tests.ranges (t_name, row_from, row_to) VALUES ('to_block_05', 101, 200);
INSERT INTO parallel_tests.ranges (t_name, row_from, row_to) VALUES ('to_block_05', 201, 300);
INSERT INTO parallel_tests.ranges (t_name, row_from, row_to) VALUES ('to_block_05', 301, 400);
INSERT INTO parallel_tests.ranges (t_name, row_from, row_to) VALUES ('to_block_05', 401, 500);

INSERT INTO parallel_tests.ranges (t_name, row_from, row_to) VALUES ('to_block_06',   1, 100);
INSERT INTO parallel_tests.ranges (t_name, row_from, row_to) VALUES ('to_block_06', 101, 200);
INSERT INTO parallel_tests.ranges (t_name, row_from, row_to) VALUES ('to_block_06', 201, 300);
INSERT INTO parallel_tests.ranges (t_name, row_from, row_to) VALUES ('to_block_06', 301, 400);
INSERT INTO parallel_tests.ranges (t_name, row_from, row_to) VALUES ('to_block_06', 401, 500);

INSERT INTO parallel_tests.ranges (t_name, row_from, row_to) VALUES ('to_block_07',   1, 100);
INSERT INTO parallel_tests.ranges (t_name, row_from, row_to) VALUES ('to_block_07', 101, 200);
INSERT INTO parallel_tests.ranges (t_name, row_from, row_to) VALUES ('to_block_07', 201, 300);
INSERT INTO parallel_tests.ranges (t_name, row_from, row_to) VALUES ('to_block_07', 301, 400);
INSERT INTO parallel_tests.ranges (t_name, row_from, row_to) VALUES ('to_block_07', 401, 500);

INSERT INTO parallel_tests.ranges (t_name, row_from, row_to) VALUES ('to_block_08',   1, 100);
INSERT INTO parallel_tests.ranges (t_name, row_from, row_to) VALUES ('to_block_08', 101, 200);
INSERT INTO parallel_tests.ranges (t_name, row_from, row_to) VALUES ('to_block_08', 201, 300);
INSERT INTO parallel_tests.ranges (t_name, row_from, row_to) VALUES ('to_block_08', 301, 400);
INSERT INTO parallel_tests.ranges (t_name, row_from, row_to) VALUES ('to_block_08', 401, 500);

INSERT INTO parallel_tests.ranges (t_name, row_from, row_to) VALUES ('to_block_09',   1, 100);
INSERT INTO parallel_tests.ranges (t_name, row_from, row_to) VALUES ('to_block_09', 101, 200);
INSERT INTO parallel_tests.ranges (t_name, row_from, row_to) VALUES ('to_block_09', 201, 300);
INSERT INTO parallel_tests.ranges (t_name, row_from, row_to) VALUES ('to_block_09', 301, 400);
INSERT INTO parallel_tests.ranges (t_name, row_from, row_to) VALUES ('to_block_09', 401, 500);

INSERT INTO parallel_tests.ranges (t_name, row_from, row_to) VALUES ('to_block_10',   1, 100);
INSERT INTO parallel_tests.ranges (t_name, row_from, row_to) VALUES ('to_block_10', 101, 200);
INSERT INTO parallel_tests.ranges (t_name, row_from, row_to) VALUES ('to_block_10', 201, 300);
INSERT INTO parallel_tests.ranges (t_name, row_from, row_to) VALUES ('to_block_10', 301, 400);
INSERT INTO parallel_tests.ranges (t_name, row_from, row_to) VALUES ('to_block_10', 401, 500);

CREATE UNIQUE INDEX ranges_name_row_fr_row_t_idx ON parallel_tests.ranges(t_name, row_from, row_to);